/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/source-items/resolve-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Url
         * @description RAD-022 第一步：解析预览，不落库。
         */
        post: operations["resolve_url_api_v1_source_items_resolve_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/source-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Source Items
         * @description 视频库列表（监控台"视频库"页）：按账号/状态过滤，id 倒序。
         */
        get: operations["list_source_items_api_v1_source_items_get"];
        put?: never;
        /**
         * Create Source Item
         * @description RAD-022 第二步：确认后创建（服务端重新 resolve，C4）。
         */
        post: operations["create_source_item_api_v1_source_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/source-items/{item_id}/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Prepare Source Item Manual
         * @description 手动转录（视频库"转写"按钮）：清 backfill 标记后投递 prepare。
         *
         *     discovered/failed 可投；其余状态 409（幂等保护，与 prepare 状态门槛一致）。
         */
        post: operations["prepare_source_item_manual_api_v1_source_items__item_id__prepare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/source-items/{item_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Transcript
         * @description 转录正文（视频库抽屉）：分段文本 + 主播名。未转写/不存在给 4xx。
         */
        get: operations["get_transcript_api_v1_source_items__item_id__transcript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/source-items/{item_id}/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Viewpoints Manual
         * @description 手动抽取观点（视频库按钮）：仅 transcribed 状态可发起，幂等由抽取服务保证。
         */
        post: operations["extract_viewpoints_manual_api_v1_source_items__item_id__extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/source-items/{item_id}/viewpoint-evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Viewpoint Evidence
         * @description RAD-084：观点证据行（含原文与时间戳，供 seek link 与 review actions）。
         */
        get: operations["get_viewpoint_evidence_api_v1_source_items__item_id__viewpoint_evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/source-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Source Accounts */
        get: operations["list_source_accounts_api_v1_source_accounts_get"];
        put?: never;
        /** Create Source Account */
        post: operations["create_source_account_api_v1_source_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/source-accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Source Account */
        patch: operations["patch_source_account_api_v1_source_accounts__account_id__patch"];
        trace?: never;
    };
    "/api/v1/live/monitors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Live Monitors
         * @description 监控看板：douyin 账号逐行状态（在播/同步/最近会话/转录）。
         */
        get: operations["get_live_monitors_api_v1_live_monitors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/security": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Security Settings */
        get: operations["get_security_settings_api_v1_settings_security_get"];
        /** Put Security Settings */
        put: operations["put_security_settings_api_v1_settings_security_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get System Status
         * @description 引擎状态（总览页）：ASR 引擎、dtk 可达性、录制器同步路数。只读探测，失败不抛。
         */
        get: operations["get_system_status_api_v1_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard
         * @description RAD-071：单请求聚合 Dashboard payload（统计卡/共识/直播间/最近观点）。
         */
        get: operations["get_dashboard_api_v1_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description RAD-089 Job Center：任务执行记录（状态/耗时/attempt/trace/错误）。
         */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transcripts/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Transcripts */
        get: operations["search_transcripts_api_v1_transcripts_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/viewpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Viewpoints
         * @description RAD-072：统一列表过滤 + 分页（items/total/page/page_size）。
         */
        get: operations["list_viewpoints_api_v1_viewpoints_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/viewpoints/{viewpoint_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Viewpoint */
        get: operations["get_viewpoint_api_v1_viewpoints__viewpoint_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Viewpoint
         * @description RAD-052：人工修正（claim/stance/horizon/topic/entity/置信度等），写审计。
         */
        patch: operations["patch_viewpoint_api_v1_viewpoints__viewpoint_id__patch"];
        trace?: never;
    };
    "/api/v1/viewpoints/{viewpoint_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Viewpoint
         * @description RAD-052：人工确认 → confirmed + 快照构建（RAD-060）+ item ready 检查。
         */
        post: operations["confirm_viewpoint_api_v1_viewpoints__viewpoint_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/viewpoints/{viewpoint_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Viewpoint
         * @description RAD-052：人工驳回 → rejected（不删数据）。
         */
        post: operations["reject_viewpoint_api_v1_viewpoints__viewpoint_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CreateSourceAccountRequest */
        CreateSourceAccountRequest: {
            /** Platform */
            platform: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Display Name */
            display_name?: string | null;
            /**
             * Discovery Mode
             * @default manual
             * @enum {string}
             */
            discovery_mode: "manual" | "auto_poll";
            /**
             * Poll Interval Sec
             * @default 3600
             */
            poll_interval_sec: number;
            /** Poll Interval Min Sec */
            poll_interval_min_sec?: number | null;
            /** Poll Interval Max Sec */
            poll_interval_max_sec?: number | null;
            /** Live Room Url */
            live_room_url?: string | null;
            /**
             * Config Json
             * @default {}
             */
            config_json: {
                [key: string]: unknown;
            };
        };
        /** CreateSourceItemRequest */
        CreateSourceItemRequest: {
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PatchSourceAccountRequest */
        PatchSourceAccountRequest: {
            /** Url */
            url?: string | null;
            /** Discovery Mode */
            discovery_mode?: ("manual" | "auto_poll") | null;
            /** Poll Interval Sec */
            poll_interval_sec?: number | null;
            /** Poll Interval Min Sec */
            poll_interval_min_sec?: number | null;
            /** Poll Interval Max Sec */
            poll_interval_max_sec?: number | null;
            /** Live Room Url */
            live_room_url?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Live Monitor Enabled */
            live_monitor_enabled?: boolean | null;
            /** Monitor Interval Sec */
            monitor_interval_sec?: number | null;
            /** Expected Schedule */
            expected_schedule?: {
                [key: string]: unknown;
            } | null;
        };
        /** ResolveUrlRequest */
        ResolveUrlRequest: {
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** ResolveUrlResponse */
        ResolveUrlResponse: {
            /** Platform */
            platform: string;
            /** External Id */
            external_id: string;
            /** Title */
            title: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Thumbnail Url */
            thumbnail_url: string | null;
            /** Item Type */
            item_type: string;
            /** Published At */
            published_at: string | null;
            /** Channel Name */
            channel_name: string | null;
            /** Subtitle Languages */
            subtitle_languages: string[];
        };
        /** SecuritySettingsPayload */
        SecuritySettingsPayload: {
            /** Discover Dispatch Stagger Max Sec */
            discover_dispatch_stagger_max_sec?: number | null;
            /** Douyin Discover Max Pages */
            douyin_discover_max_pages?: number | null;
            /** Proxy Pool */
            proxy_pool?: string[] | null;
        };
        /** SourceAccountResponse */
        SourceAccountResponse: {
            /** Id */
            id: number;
            /** Creator Id */
            creator_id: number;
            /** Platform */
            platform: string;
            /** External Id */
            external_id: string;
            /** Handle */
            handle: string | null;
            /** Url */
            url: string | null;
            /** Live Room Url */
            live_room_url: string | null;
            /** Discovery Mode */
            discovery_mode: string;
            /** Poll Interval Sec */
            poll_interval_sec: number;
            /** Poll Interval Min Sec */
            poll_interval_min_sec: number | null;
            /** Poll Interval Max Sec */
            poll_interval_max_sec: number | null;
            /** Enabled */
            enabled: boolean;
            /** Live Monitor Enabled */
            live_monitor_enabled: boolean;
            /** Monitor Interval Sec */
            monitor_interval_sec: number;
            /** Expected Schedule */
            expected_schedule: {
                [key: string]: unknown;
            } | null;
            /** Last Success At */
            last_success_at: string | null;
            /** Failure Count */
            failure_count: number;
        };
        /** SourceItemResponse */
        SourceItemResponse: {
            /** Id */
            id: number;
            /** Source Account Id */
            source_account_id: number;
            /** External Item Id */
            external_item_id: string;
            /** Item Type */
            item_type: string;
            /** Title */
            title: string | null;
            /** Canonical Url */
            canonical_url: string | null;
            /** Thumbnail Url */
            thumbnail_url: string | null;
            /** Published At */
            published_at: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ViewpointPatch */
        ViewpointPatch: {
            /** Claim */
            claim?: string | null;
            /** Stance */
            stance?: string | null;
            /** Horizon */
            horizon?: string | null;
            /** Topic Id */
            topic_id?: number | null;
            /** Entity Id */
            entity_id?: number | null;
            /** Confidence */
            confidence?: number | null;
            /** Importance */
            importance?: number | null;
            /** Reason */
            reason?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    resolve_url_api_v1_source_items_resolve_url_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveUrlRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveUrlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_source_items_api_v1_source_items_get: {
        parameters: {
            query?: {
                account_id?: number | null;
                status?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_source_item_api_v1_source_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSourceItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prepare_source_item_manual_api_v1_source_items__item_id__prepare_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transcript_api_v1_source_items__item_id__transcript_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_viewpoints_manual_api_v1_source_items__item_id__extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_viewpoint_evidence_api_v1_source_items__item_id__viewpoint_evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_source_accounts_api_v1_source_accounts_get: {
        parameters: {
            query?: {
                platform?: string | null;
                enabled?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceAccountResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_source_account_api_v1_source_accounts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSourceAccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceAccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_source_account_api_v1_source_accounts__account_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchSourceAccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceAccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_live_monitors_api_v1_live_monitors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_security_settings_api_v1_settings_security_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    put_security_settings_api_v1_settings_security_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecuritySettingsPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_system_status_api_v1_system_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_dashboard_api_v1_dashboard_get: {
        parameters: {
            query?: {
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
                job_type?: string | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_transcripts_api_v1_transcripts_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_viewpoints_api_v1_viewpoints_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                sort?: string;
                order?: "asc" | "desc";
                date_from?: string | null;
                date_to?: string | null;
                creator_id?: number | null;
                topic_id?: number | null;
                stance?: string | null;
                confidence_min?: number | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_viewpoint_api_v1_viewpoints__viewpoint_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                viewpoint_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_viewpoint_api_v1_viewpoints__viewpoint_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                viewpoint_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewpointPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_viewpoint_api_v1_viewpoints__viewpoint_id__confirm_post: {
        parameters: {
            query?: {
                reason?: string | null;
            };
            header?: never;
            path: {
                viewpoint_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_viewpoint_api_v1_viewpoints__viewpoint_id__reject_post: {
        parameters: {
            query?: {
                reason?: string | null;
            };
            header?: never;
            path: {
                viewpoint_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
