"""source account live monitor fields

Revision ID: 07402f07249c
Revises: backfill_channel_urls
Create Date: 2026-09-17 20:34:24.533920

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07402f07249c'
down_revision: str | Sequence[str] | None = 'backfill_channel_urls'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_account', sa.Column('live_monitor_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('source_account', sa.Column('monitor_interval_sec', sa.Integer(), server_default='300', nullable=False))
    op.add_column('source_account', sa.Column('expected_schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_account', 'expected_schedule')
    op.drop_column('source_account', 'monitor_interval_sec')
    op.drop_column('source_account', 'live_monitor_enabled')
    # ### end Alembic commands ###
