"""create all prd core tables

Revision ID: 274c026452c4
Revises: 
Create Date: 2026-09-16 22:37:12.707955

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '274c026452c4'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.BigInteger(), nullable=False),
    sa.Column('before_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('creator',
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_creator'))
    )
    op.create_table('entity',
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('canonical_name', sa.String(length=200), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('market', sa.String(length=30), nullable=True),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity')),
    sa.UniqueConstraint('canonical_name', name=op.f('uq_entity_canonical_name'))
    )
    op.create_table('prompt_version',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('schema_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_version')),
    sa.UniqueConstraint('name', 'version', name='uq_prompt_version_name_version')
    )
    op.create_table('topic',
    sa.Column('canonical_name', sa.String(length=200), nullable=False),
    sa.Column('topic_type', sa.String(length=30), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topic')),
    sa.UniqueConstraint('canonical_name', name=op.f('uq_topic_canonical_name')),
    comment='主题词典：canonical_name 唯一'
    )
    op.create_table('source_account',
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('handle', sa.String(length=200), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('discovery_mode', sa.String(length=30), nullable=False),
    sa.Column('poll_interval_sec', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creator.id'], name=op.f('fk_source_account_creator_id_creator'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_account')),
    sa.UniqueConstraint('platform', 'external_id', name='uq_source_account_platform_external')
    )
    op.create_table('topic_consensus_daily',
    sa.Column('topic_id', sa.BigInteger(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('creator_count', sa.Integer(), nullable=False),
    sa.Column('bullish_count', sa.Integer(), nullable=False),
    sa.Column('neutral_count', sa.Integer(), nullable=False),
    sa.Column('bearish_count', sa.Integer(), nullable=False),
    sa.Column('bullish_ratio', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('net_stance_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('disagreement_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], name=op.f('fk_topic_consensus_daily_topic_id_topic'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_id', 'trade_date', name=op.f('pk_topic_consensus_daily'))
    )
    op.create_table('source_item',
    sa.Column('source_account_id', sa.BigInteger(), nullable=False),
    sa.Column('external_item_id', sa.String(length=300), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['source_account_id'], ['source_account.id'], name=op.f('fk_source_item_source_account_id_source_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_item')),
    sa.UniqueConstraint('source_account_id', 'external_item_id', name='uq_source_item_account_external')
    )
    op.create_table('job_run',
    sa.Column('job_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_item_id', sa.BigInteger(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('worker', sa.String(length=100), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['source_item_id'], ['source_item.id'], name=op.f('fk_job_run_source_item_id_source_item'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_run'))
    )
    op.create_index(op.f('ix_job_run_trace_id'), 'job_run', ['trace_id'], unique=False)
    op.create_table('media_asset',
    sa.Column('source_item_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_type', sa.String(length=30), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['source_item_id'], ['source_item.id'], name=op.f('fk_media_asset_source_item_id_source_item'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_asset'))
    )
    op.create_index('ix_media_asset_source_item', 'media_asset', ['source_item_id'], unique=False)
    op.create_table('transcript_segment',
    sa.Column('source_item_id', sa.BigInteger(), nullable=False),
    sa.Column('speaker_label', sa.String(length=100), nullable=True),
    sa.Column('start_ms', sa.BigInteger(), nullable=False),
    sa.Column('end_ms', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('asr_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['source_item_id'], ['source_item.id'], name=op.f('fk_transcript_segment_source_item_id_source_item'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcript_segment'))
    )
    op.create_index('ix_transcript_segment_item_seq', 'transcript_segment', ['source_item_id', 'sequence_no'], unique=False)
    op.create_table('viewpoint',
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('source_item_id', sa.BigInteger(), nullable=False),
    sa.Column('topic_id', sa.BigInteger(), nullable=True),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('stance', sa.String(length=30), nullable=False),
    sa.Column('horizon', sa.String(length=30), nullable=False),
    sa.Column('conditional', sa.Boolean(), nullable=False),
    sa.Column('importance', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('change_type', sa.String(length=30), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('extractor_version', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_viewpoint_confidence_range')),
    sa.CheckConstraint('importance >= 0 AND importance <= 1', name=op.f('ck_viewpoint_importance_range')),
    sa.ForeignKeyConstraint(['creator_id'], ['creator.id'], name=op.f('fk_viewpoint_creator_id_creator'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], name=op.f('fk_viewpoint_entity_id_entity'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_item_id'], ['source_item.id'], name=op.f('fk_viewpoint_source_item_id_source_item'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], name=op.f('fk_viewpoint_topic_id_topic'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_viewpoint'))
    )
    op.create_index('ix_viewpoint_creator_topic', 'viewpoint', ['creator_id', 'topic_id'], unique=False)
    op.create_index('ix_viewpoint_creator_topic_asof', 'viewpoint', ['creator_id', 'topic_id', 'as_of_date'], unique=False)
    op.create_index('ix_viewpoint_entity', 'viewpoint', ['entity_id'], unique=False)
    op.create_index('ix_viewpoint_source_item', 'viewpoint', ['source_item_id'], unique=False)
    op.create_table('creator_topic_snapshot',
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('topic_id', sa.BigInteger(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('latest_viewpoint_id', sa.BigInteger(), nullable=True),
    sa.Column('stance', sa.String(length=30), nullable=True),
    sa.Column('horizon', sa.String(length=30), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('change_type', sa.String(length=30), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creator.id'], name=op.f('fk_creator_topic_snapshot_creator_id_creator'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['latest_viewpoint_id'], ['viewpoint.id'], name=op.f('fk_creator_topic_snapshot_latest_viewpoint_id_viewpoint'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], name=op.f('fk_creator_topic_snapshot_topic_id_topic'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('creator_id', 'topic_id', 'snapshot_date', name=op.f('pk_creator_topic_snapshot')),
    comment='每人物每主题每日最新有效观点快照（PRD 8.1）'
    )
    op.create_table('viewpoint_evidence',
    sa.Column('viewpoint_id', sa.BigInteger(), nullable=False),
    sa.Column('transcript_segment_id', sa.BigInteger(), nullable=False),
    sa.Column('start_ms', sa.BigInteger(), nullable=False),
    sa.Column('end_ms', sa.BigInteger(), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('evidence_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['transcript_segment_id'], ['transcript_segment.id'], name=op.f('fk_viewpoint_evidence_transcript_segment_id_transcript_segment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewpoint_id'], ['viewpoint.id'], name=op.f('fk_viewpoint_evidence_viewpoint_id_viewpoint'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_viewpoint_evidence')),
    sa.UniqueConstraint('viewpoint_id', 'evidence_order', name='uq_evidence_viewpoint_order')
    )
    op.create_index('ix_evidence_segment', 'viewpoint_evidence', ['transcript_segment_id'], unique=False)
    op.create_index('ix_evidence_viewpoint', 'viewpoint_evidence', ['viewpoint_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_evidence_viewpoint', table_name='viewpoint_evidence')
    op.drop_index('ix_evidence_segment', table_name='viewpoint_evidence')
    op.drop_table('viewpoint_evidence')
    op.drop_table('creator_topic_snapshot')
    op.drop_index('ix_viewpoint_source_item', table_name='viewpoint')
    op.drop_index('ix_viewpoint_entity', table_name='viewpoint')
    op.drop_index('ix_viewpoint_creator_topic_asof', table_name='viewpoint')
    op.drop_index('ix_viewpoint_creator_topic', table_name='viewpoint')
    op.drop_table('viewpoint')
    op.drop_index('ix_transcript_segment_item_seq', table_name='transcript_segment')
    op.drop_table('transcript_segment')
    op.drop_index('ix_media_asset_source_item', table_name='media_asset')
    op.drop_table('media_asset')
    op.drop_index(op.f('ix_job_run_trace_id'), table_name='job_run')
    op.drop_table('job_run')
    op.drop_table('source_item')
    op.drop_table('topic_consensus_daily')
    op.drop_table('source_account')
    op.drop_table('topic')
    op.drop_table('prompt_version')
    op.drop_table('entity')
    op.drop_table('creator')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
